### ISSUE TITLE
First pass of train command

### ISSUE THREAD

**Issue by dimenwarper** [njpataki/weasl#2]
Train a classifier for each rule defined in rules/classifier_name.py
using the yaml classifier configuration file to define featurizers and classifier classes

E.g. 

$ weasl train new_construction --train-file=data/training_sets/train_permits.tsv

This will create a set of classifiers in the classifier/ directory, labeled with the classifier name, the rule name, and the training set file name

**Comment by njpataki** [comment]
https://github.com/njpataki/weasl/commit/2e42a392b2ecb3125365513a37bc95996db8f44d
